// This file was generated by gir (d121f7e) from gir-files (71d73f0)
// DO NOT EDIT

mod key_file;
pub use self::key_file::KeyFile;

#[cfg(feature = "v2_40")]
mod variant_dict;
#[cfg(feature = "v2_40")]
pub use self::variant_dict::VariantDict;

mod enums;
pub use self::enums::KeyFileError;
pub use self::enums::OptionArg;

mod flags;
pub use self::flags::FormatSizeFlags;
pub use self::flags::FORMAT_SIZE_DEFAULT;
pub use self::flags::FORMAT_SIZE_LONG_FORMAT;
pub use self::flags::FORMAT_SIZE_IEC_UNITS;
pub use self::flags::KeyFileFlags;
pub use self::flags::KEY_FILE_NONE;
pub use self::flags::KEY_FILE_KEEP_COMMENTS;
pub use self::flags::KEY_FILE_KEEP_TRANSLATIONS;
pub use self::flags::OptionFlags;
pub use self::flags::OPTION_FLAG_NONE;
pub use self::flags::OPTION_FLAG_HIDDEN;
pub use self::flags::OPTION_FLAG_IN_MAIN;
pub use self::flags::OPTION_FLAG_REVERSE;
pub use self::flags::OPTION_FLAG_NO_ARG;
pub use self::flags::OPTION_FLAG_FILENAME;
pub use self::flags::OPTION_FLAG_OPTIONAL_ARG;
pub use self::flags::OPTION_FLAG_NOALIAS;

pub mod functions;

#[doc(hidden)]
pub mod traits {
}
